---
- hosts: server
  roles:
    - role: docker
    - role: etcd

- hosts: master  
  roles:
    - role: master

- hosts: minion
  roles:
    - role: minion

- hosts: server
  roles:
    - role: post_config
