---
# tasks file for osm_dockerEngine

- name: install docker with yum
  include: install-centos.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Stop and Disable firewalld
  systemd:
   name: firewalld
   state: stopped
   enabled: false
  become: true
